### ISSUE TITLE
“打开小程序”后显示“网络不给力，请稍后再试”

### ISSUE THREAD

**Issue by qiuhao1991** [mpaas-demo/android-tinyapp#1]
将demo安装后在真机上运行，动态权限全部允许，点击“打开小程序”，显示“网络不给力，请稍后再试”。
然后log中有报错：
 E/DynamicRelease: [URGENT_DISP_6] com.alipay.mobile.common.rpc.RpcException: RPCException: [7001] 
然后返回点击“开启自定义加载页”，显示fail，
是否缺少配置？
更多log如下：

2020-04-16 15:32:41.472 12805-13126/com.mpaas.demo E/DynamicRelease: [URGENT_DISP_2] com.alipay.mobile.common.rpc.RpcException: RPCException: [7001] : 
        at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.preProcessResponse(RpcInvokerUtil.java:90)
        at com.alipay.mobile.common.rpc.protocol.protobuf.PBDeserializer.parser(PBDeserializer.java:36)
        at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:221)
        at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:146)
        at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:67)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy4.getUnionResource(Unknown Source)
        at com.alipay.android.phone.mobilecommon.dynamicrelease.nebula.NebulaCenterOperator.rpcRequest(NebulaCenterOperator.java:167)
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.rpcCall(MPAppBizRpcImpl.java:118)
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.app(MPAppBizRpcImpl.java:51)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.request(H5BaseAppProvider.java:650)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.updateAppWithReqFinally(H5BaseAppProvider.java:584)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.access$000(H5BaseAppProvider.java:55)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider$1.run(H5BaseAppProvider.java:150)
        at com.alipay.mobile.framework.pipeline.analysis.AnalysedRunnable.run(AnalysedRunnable.java:86)
        at com.alipay.mobile.framework.pipeline.DelayedRunnable.run(DelayedRunnable.java:65)
        at com.alipay.mobile.framework.service.common.threadpool.TaskPoolRunnable.run(TaskPoolRunnable.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-04-16 15:32:41.484 12805-13126/com.mpaas.demo E/RPCStart|Fail: [URGENT_DISP_2] java.lang.IllegalStateException: result == null
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.rpcCall(MPAppBizRpcImpl.java:125)
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.app(MPAppBizRpcImpl.java:51)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.request(H5BaseAppProvider.java:650)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.updateAppWithReqFinally(H5BaseAppProvider.java:584)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.access$000(H5BaseAppProvider.java:55)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider$1.run(H5BaseAppProvider.java:150)
        at com.alipay.mobile.framework.pipeline.analysis.AnalysedRunnable.run(AnalysedRunnable.java:86)
        at com.alipay.mobile.framework.pipeline.DelayedRunnable.run(DelayedRunnable.java:65)
        at com.alipay.mobile.framework.service.common.threadpool.TaskPoolRunnable.run(TaskPoolRunnable.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-04-16 15:32:42.500 1558-1629/? E/LocationAccessPolicy: canAccessCellLocation return false. uid = 1000, pkgName = android
2020-04-16 15:32:43.970 1059-1164/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
2020-04-16 15:32:43.970 1059-1164/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
2020-04-16 15:32:43.970 1059-1164/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
2020-04-16 15:32:43.970 1059-1164/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found

**Comment by qiuhao1991** [comment]
真机为  vivo X21A，Android版本9

**Comment by glcrazier** [comment]
@qiuhao1991 按照readme，使用命令行编译即可，如果用IDE编译，请参考aar接入文档
